"""Module to handle the reading of PDF files and provide it's information
as text or visual information.
"""
from typing import Iterator
from dataclasses import dataclass

import pandas as pd
import numpy as np
import pdfplumber

from .processors import get_data_inside_boundaries

DEFAULT_BOUNDARY_LEFT = 0.0
DEFAULT_BOUNDARY_TOP = 0.0
DEFAULT_BOUNDARY_RIGHT = 1.0
DEFAULT_BOUNDARY_BOTTOM = 1.0
DEFAULT_WRITABLE_BOUNDARIES = (
    DEFAULT_BOUNDARY_LEFT,
    DEFAULT_BOUNDARY_TOP,
    DEFAULT_BOUNDARY_RIGHT,
    DEFAULT_BOUNDARY_BOTTOM
)

PDFPLUMBER_WORD_LEVEL = 5
LINE_TOLERANCE_RATE = 0.4
RIGHT_ALIGN_TOLERANCE_RATE = 0.05
RIGHT_ALIGN_CENTER_RATE = 0.75
CENTER_TOLERANCE_RATE = 0.1
LEFT_ALIGN_CENTER_TOLERANCE_RATE = 0.1
COLUMN_SEPARATION_RATE = 0.04
COLUMN_OVERLAP_TOLERANCE_RATE = 0.04


@dataclass
class GroupState:
    """Store state when searching groups while reconstrucing text of document."""

    line_cols: dict[str, dict[str, int]]
    group_cols: dict[str, dict[str, int]]
    prev_values: dict[str, int|bool|None]
    centered: dict[str, bool|None]
    pass_through_center: dict[str, bool|None]
    tolerance: float
    group_num: int

class DataReconstructor():
    """Class to fix issues generated by Pdfplumber in text reconstruction.

    This class reconstruct the text of the page, creating new groups and
    adding columns to the data.
    """

    def __init__(self,
                 data: pd.DataFrame,
                 writable_boundaries: tuple[float,float,float,float] = DEFAULT_WRITABLE_BOUNDARIES):
        self.data = data.copy()

        if 'right' not in self.data and 'left' in self.data:
            self.data['right'] = self.data['left'] + self.data['width']
        if 'bottom' not in self.data and 'top' in self.data:
            self.data['bottom'] = self.data['top'] + self.data['height']

        self.writable_min_x = writable_boundaries[0]
        self.writable_max_x = writable_boundaries[2]
        self.writable_width = self.writable_max_x - self.writable_min_x
        self.writable_center = self.writable_min_x + self.writable_width * 0.5

    def get_reconstructed(self) -> pd.DataFrame:
        """Return the reconstructed visual data of the page by fixing the issues of
        the original data provided by PdfPlumber."""
        self.__assign_line_number()
        self.__assign_column_number()
        self.__assign_column_position()
        self.__assign_group_number()
        self.__merge_columns()

        return self.data

    def __assign_line_number(self):
        self.data['line'] = pd.Series(dtype='int')
        words = self.data[self.data['level'] == PDFPLUMBER_WORD_LEVEL].sort_values(by=['top'])

        current_line_num = -1
        current_min_y, current_max_y = 0, 0
        for word_idx, word in words.iterrows():
            word_top = word['top']
            word_bottom = word['top'] + word['height']

            if self.__is_same_line(current_min_y, current_max_y, word_top, word['height']):
                current_min_y = min(current_min_y, word_top)
                current_max_y = max(current_max_y, word_bottom)
            else:
                current_line_num += 1
                current_min_y, current_max_y = word_top, word_bottom

            self.data.loc[word_idx, 'line'] = current_line_num

    def __is_same_line(self, line_top: float, line_bottom: float, word_top: float,
                       word_height: float) -> bool:
        return (
            line_top + word_height * LINE_TOLERANCE_RATE < word_top + word_height
            and line_bottom - word_height * LINE_TOLERANCE_RATE > word_top
        )

    def __assign_column_number(self, min_words_per_col:int=1):
        self.data['column'] = pd.Series(dtype='int')
        tolerance = self.writable_width * COLUMN_SEPARATION_RATE

        for _, line_words in self.data.groupby('line'):
            col_number = -1
            current_col = {}

            sorted_words = line_words.sort_values(by='left')
            num_words = len(sorted_words)
            for i, (idx, word) in enumerate(sorted_words.iterrows()):
                word_left = word['left']
                word_right = word['left'] + word['width']

                if (current_col and
                    num_words - i <= min_words_per_col and
                    self.__words_are_right_aligned(sorted_words[i:])):
                    # When too few words are left and aligned right consider them as the same colum
                    current_col['maxX'] = word_right
                elif (current_col and
                    word_left - current_col['maxX'] < tolerance):
                    # It is close enough to be in the same column
                    current_col['maxX'] = word_right
                else:
                    col_number += 1
                    current_col = {'maxX': word_right, 'minX': word_left}

                self.data.loc[idx, 'column'] = col_number

    def __assign_column_position(self):
        self.data['col_position'] = pd.Series(dtype='int')

        grouped = self.data.groupby(['line', 'column']).agg({'left': 'min', 'right': 'max'})
        for (line, column), values in grouped.iterrows():
            position = -1
            if self.__column_is_aligned_left(values['left'], values['right']):
                position = 0
            elif self.__column_is_aligned_right(values['left'], values['right']):
                position = 1

            words_indices = self.data[(self.data['line'] == line) & (self.data['column'] == column)]
            self.data.loc[words_indices.index, 'col_position'] = position

    def __words_are_right_aligned(self, words:pd.DataFrame) -> bool:
        left = words['left'].min()
        right = words['right'].max()
        center = left + (right - left) * 0.5

        return (
            abs(self.writable_max_x - right) < self.writable_width * RIGHT_ALIGN_TOLERANCE_RATE and
            center > self.writable_width * RIGHT_ALIGN_CENTER_RATE
        )

    def __column_is_centered(self, min_x, max_x):
        center_rate = (self.writable_center - min_x) / (max_x - self.writable_center)
        return (
            min_x < self.writable_center < max_x and
            abs(1.0 - center_rate) < CENTER_TOLERANCE_RATE
        )

    def __column_passes_through_center(self, min_x, max_x):
        return min_x < self.writable_center < max_x

    def __column_is_aligned_left(self, min_x, max_x):
        col_center = min_x + (max_x - min_x) * 0.5
        left_align_center_tolerance = self.writable_width * LEFT_ALIGN_CENTER_TOLERANCE_RATE

        return (
            col_center < self.writable_center + left_align_center_tolerance and
            not min_x > self.writable_center
        )

    def __column_is_aligned_right(self, min_x, max_x):
        col_center = min_x + (max_x - min_x) * 0.5

        return col_center > self.writable_center

    def __assign_group_number(self):
        self.data['group'] = pd.Series(dtype='int')
        tolerance = self.writable_width * COLUMN_OVERLAP_TOLERANCE_RATE

        state = GroupState(
            line_cols=None,
            group_cols=None,
            prev_values={'num_cols': None, 'new_group': False},
            centered={'prev': None, 'curr': None},
            pass_through_center={'prev': None, 'curr': None},
            tolerance=tolerance,
            group_num=0,
        )

        for _, line_words in self.data.groupby('line'):
            state.line_cols = self.__extract_line_columns(line_words)
            state.centered['curr'] = False
            state.pass_through_center['curr'] = False
            for _, col in state.line_cols.items():
                if self.__column_is_centered(col['minX'], col['maxX']):
                    state.centered['curr'] = True
                if self.__column_passes_through_center(col['minX'], col['maxX']):
                    state.pass_through_center['curr'] = True

            new_group = self.__is_new_group(state)

            if new_group:
                state.group_num += 1

            self.data.loc[line_words.index, 'group'] = state.group_num

            # Update tracking variables
            state.prev_values['num_cols'] = len(state.line_cols)
            state.centered['prev'] = state.centered['curr']
            state.pass_through_center['prev'] = state.pass_through_center['curr']
            state.prev_values['new_group'] = new_group

            if state.group_cols is None or new_group:
                state.group_cols = state.line_cols
            else:
                self.__expand_group_columns(state.group_cols, state.line_cols)

    def __extract_line_columns(self, line_words):
        """Return a dict mapping column to position, minX, maxX."""
        columns_info = {}
        grouped = line_words.groupby('column').agg({
            'col_position': 'max',
            'left': 'min',
            'right': 'max',
            'top': 'min',
            'bottom': 'max',
        })

        for column, values in grouped.iterrows():
            columns_info[column] = {
                'position_max': values['col_position'],
                'minX': values['left'],
                'maxX': values['right'],
                'minY': values['top'],
                'maxY': values['bottom'],
            }

        return columns_info

    def __is_new_group(self, state:GroupState):
        if (state.group_cols is None or
            state.prev_values['num_cols'] is None or
            state.centered['prev'] is None):
            return False

        if len(state.group_cols) != len(state.line_cols):
            if state.pass_through_center['curr'] or state.pass_through_center['prev']:
                return True
        elif (state.centered['curr'] != state.centered['prev'] and
              state.line_cols.get(0).get('position_max') == 0):
            return True

        for g_col in state.group_cols:
            for l_col in state.line_cols:
                g_position_max = state.group_cols[g_col]['position_max']
                if state.line_cols[l_col]['position_max'] != g_position_max:
                    continue

                if (not self.__columns_wrap_each_other(
                        state.line_cols[l_col], state.group_cols[g_col], state.tolerance) and
                    not state.prev_values['new_group']):
                    return True
        return False

    def __columns_wrap_each_other(self, col1, col2, tolerance):
        return (
            (col1['minX'] > col2['minX'] - tolerance and col1['maxX'] < col2['maxX'] + tolerance) or
            (col2['minX'] > col1['minX'] - tolerance and col2['maxX'] < col1['maxX'] + tolerance)
        )

    def __expand_group_columns(self, group_cols, line_cols):
        for g_col in group_cols:
            position_max = group_cols[g_col]['position_max']
            for l_col in line_cols:
                if line_cols[l_col]['position_max'] != position_max:
                    continue

                group_cols[g_col]['minX'] = min(group_cols[g_col]['minX'], line_cols[l_col]['minX'])
                group_cols[g_col]['maxX'] = max(group_cols[g_col]['maxX'], line_cols[l_col]['maxX'])
                group_cols[g_col]['minY'] = min(group_cols[g_col]['minY'], line_cols[l_col]['minY'])
                group_cols[g_col]['maxY'] = max(group_cols[g_col]['maxY'], line_cols[l_col]['maxY'])

        if len(line_cols) > len(group_cols):
            for l_col in line_cols:
                if l_col not in group_cols:
                    group_cols[l_col] = line_cols[l_col]

    def __merge_columns(self):
        for group, values in self.data.groupby('group'):
            columns_edges = values.groupby('col_position').agg({'left': 'min', 'right': 'max'})
            if len(columns_edges) > 1:
                pivot = columns_edges.iloc[0]
                for col_position in columns_edges.index[1:]:
                    if pivot['right'] > columns_edges.loc[col_position, 'left']:
                        self.data.loc[self.data['group'] == group, 'col_position'] = pivot.name

class PdfPlumberPage():
    """This class stores the text extracted by Pdfplumber and provides
    methods to process it.
    """

    def __init__(self, page:pdfplumber.page.Page):
        self.page = page.dedupe_chars()

        self.data = self.__get_data_from_page()

        self.__normalize_data()

        w_boundaries = self.__get_writable_boundaries()
        reconstructor = DataReconstructor(self.data, w_boundaries)
        self.data = reconstructor.get_reconstructed()

    def get_text(self, remove_headers: bool=False, boundaries:dict[str,float]=None) -> str:
        """Return the reconstructed text of the page (without Pdfplumber errors)."""
        if remove_headers:
            data = get_data_inside_boundaries(self.data, boundaries)
        else:
            data = self.data
        data = data.sort_values(['line', 'left'])
        t_by_line = data.groupby(['group', 'col_position', 'line'])['text'].apply(' '.join)
        t_by_column = t_by_line.groupby(['group', 'col_position']).apply('\n'.join)
        t_by_group = t_by_column.groupby('group').apply('\n'.join)

        return '\n'.join(t_by_group)

    def get_raw_text(self, remove_headers: bool=False, boundaries:dict[str,float]=None) -> str:
        """Return the text as returned by pdfplumber."""
        if remove_headers and boundaries is not None:
            x0 = boundaries['left'] * self.page.width
            top = boundaries['top'] * self.page.height
            x1 = boundaries['right'] * self.page.width
            bottom = boundaries['bottom'] * self.page.height

            page_content = self.page.crop((x0, top, x1, bottom))
        else:
            page_content = self.page

        plumber_lines = page_content.extract_text_lines(use_text_flow=True)
        text = '\n'.join([line['text'] for line in plumber_lines])

        return text

    def get_words(self, suffix = '') -> pd.DataFrame:
        """Get the reconstructed text and split it into words into a dataframe."""
        text = self.get_text()
        if text == '':
            return pd.DataFrame(columns=['word'])

        indices = self.get_indices()
        words = [(idx, f'{w}{suffix}') for idx, w in zip(indices, text.split())]
        df_words = pd.DataFrame(words, columns=['visual_idx', 'word'])
        df_words.set_index('visual_idx', inplace=True)

        return df_words

    def get_indices(self) -> list[int]:
        """Return the indices of the reconstructed data."""
        data = self.data.sort_values(['line', 'left']).reset_index()
        indices_by_line = data.groupby(['group', 'col_position', 'line'])['index'].agg(list)
        indices_by_colum = indices_by_line.groupby(['group', 'col_position']).sum()
        indices_by_group = indices_by_colum.groupby('group').sum()

        return list(indices_by_group.sum())

    def get_data(self) -> pd.DataFrame:
        """Get the full DataFrame of pdfplumber processed info."""
        return self.data

    def __get_data_from_page(self) -> pd.DataFrame:
        rects = self.page.extract_words()

        if not rects:
            data = pd.DataFrame(columns=['text', 'left', 'right', 'top', 'doctop', 'bottom',
                                         'upright', 'height', 'width', 'direction', 'level'])
        else:
            data = pd.DataFrame(rects)
            data = data.rename(columns={'x0': 'left', 'x1': 'right'})
            data['level'] = pd.Series([5]*data.shape[0], dtype='int')

        data = self.__regroup_words(data)

        return data

    def __normalize_data(self):
        width = self.page.width
        height = self.page.height
        self.data['left'] = self.data['left'] / width
        self.data['right'] = self.data['right'] / width
        self.data['width'] = self.data['width'] / width
        self.data['top'] = self.data['top'] / height
        self.data['bottom'] = self.data['bottom'] / height
        self.data['height'] = self.data['height'] / height

    def __get_writable_boundaries(self):
        min_x = self.data['left'].min()
        min_y = self.data['top'].min()
        max_x = self.data['right'].max()
        max_y = self.data['bottom'].max()

        return (min_x, min_y, max_x, max_y)

    def __regroup_words(self, data):
        remove_indices = []
        for _, values in data.groupby('doctop'):
            separation = values.iloc[1:]['left'].values - values.iloc[:-1]['right'].values
            should_merge = np.concatenate((np.array([False]), separation < 0.1))
            if should_merge.any():
                for idx in values.index[should_merge]:
                    data.loc[idx-1] = pd.Series(
                        {
                            'text': data.loc[idx-1, 'text'] + data.loc[idx, 'text'],
                            'left': data.loc[idx-1, 'left'],
                            'right': data.loc[idx, 'right'],
                            'top': min(data.loc[idx-1, 'top'], data.loc[idx, 'top']),
                            'doctop': data.loc[idx, 'doctop'],
                            'bottom': max(data.loc[idx-1, 'bottom'], data.loc[idx, 'bottom']),
                            'upright': data.loc[idx, 'upright'],
                            'height': max(data.loc[idx-1, 'height'], data.loc[idx, 'height']),
                            'width': data.loc[idx-1, 'width'] + data.loc[idx, 'width'],
                            'direction': data.loc[idx, 'direction'],
                            'level': data.loc[idx, 'level'],
                        }
                    )
                    remove_indices.append(idx)
        data = data.drop(remove_indices).reset_index(drop=True)

        return data

class PdfPlumberParser():
    """This parser uses PdfPlumber to convert a PDF file into text.

    A custom layer of text reconstruction is added to address issues with wource library

    :param file_path: The path of the file to be parsed.
    :type file_path: str
    """
    def __init__(self, file_path: str):
        self.file_path = file_path

        self.reader = pdfplumber.open(file_path)

    def get_raw_text(self, page_separator: str = '\n', remove_headers:bool = False,
                 boundaries:dict[str,float]=None) -> str:
        """Return the full text of the file as extracted by pdfplumber.

        :param page_separator: String to be added to separate each page,
            defaults to ''.
        :type page_separator: str, optional

        :return: A string of all the text from the document
        :rtype: str
        """
        text = ''
        for _, page in enumerate(self.reader.pages, start=1):
            page = PdfPlumberPage(page)
            text += page.get_raw_text(remove_headers, boundaries) + page_separator

        return text

    def get_text(self, page_separator: str = '\n', remove_headers:bool = False,
                 boundaries:dict[str,float]=None) -> str:
        """Return the full text with pdfplumber but applyint custom text reconstruction

        :param page_separator: String to be added to separate each page,
            defaults to '\n'.
        :type page_separator: str, optional

        :return: A string of all the text from the document
        :rtype: str
        """
        text = ''
        for _, page in enumerate(self.reader.pages, start=1):
            page = PdfPlumberPage(page)
            text += page.get_text(remove_headers, boundaries) + page_separator

        return text

    def get_num_pages(self) -> int:
        """Return the number of pages of the document."""
        return len(self.reader.pages)

    def get_pages(self) -> Iterator[PdfPlumberPage]:
        """Read the document and return the text of each page as an Iterator.

        :return: An Iterator that yields the text of each page at a time
        :rtype: Iterator[PdfPlumberPage]
        """
        for _, page in enumerate(self.reader.pages, start=1):
            yield PdfPlumberPage(page)

    def get_page(self, page_num: int):
        """Return a specific page of the document."""
        return PdfPlumberPage(self.reader.pages[page_num])
